package repository

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/AntoCandela/ai-agent-log-hub/backend/internal/model"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// SessionFilters holds optional filter criteria for listing sessions.
// Each field is either a zero value (meaning "don't filter on this") or a
// pointer (nil = don't filter). This lets callers mix and match any combination
// of filters without needing many different query methods.
type SessionFilters struct {
	// AgentID, when non-empty, restricts results to this agent.
	AgentID string
	// Status, when non-empty, restricts results to sessions with this status (e.g. "active", "closed").
	Status string
	// ProjectDir, when non-nil, restricts results to sessions with this project directory path.
	ProjectDir *string
	// Pinned, when non-nil, restricts results to pinned (true) or unpinned (false) sessions.
	Pinned *bool
}

// SessionRepo provides database access for session records.
type SessionRepo struct {
	db *pgxpool.Pool
}

// NewSessionRepo creates a new SessionRepo backed by the given pool.
func NewSessionRepo(db *pgxpool.Pool) *SessionRepo {
	return &SessionRepo{db: db}
}

// FindActiveByToken returns the active session for the given agent and session
// token, or nil if none exists.
//
// This is the core of "session resolution": the caller provides an agent ID and
// a session token (an opaque string the agent uses to identify its session).
// The query looks for a session that is still 'active' — if it finds one, the
// caller reuses it; if not, a new session is created (see SessionService.ResolveSession).
//
// The WHERE clause requires all three conditions (agent_id, session_token, AND
// status = 'active') so that a closed session with the same token is not reused.
func (r *SessionRepo) FindActiveByToken(ctx context.Context, agentID, sessionToken string) (*model.Session, error) {
	// Query: find the one active session matching this agent + token combination.
	const q = `
		SELECT session_id, session_token, agent_id, status,
		       project_dir, git_branch,
		       started_at, ended_at, last_event_at,
		       event_count, pinned
		FROM sessions
		WHERE agent_id      = $1
		  AND session_token = $2
		  AND status        = 'active'`

	row := r.db.QueryRow(ctx, q, agentID, sessionToken)
	s, err := scanSession(row)
	if err != nil {
		if isNoRows(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("SessionRepo.FindActiveByToken: %w", err)
	}
	return s, nil
}

// Create inserts a new session row and populates session_id, started_at, and
// last_event_at from the database RETURNING clause.
//
// RETURNING is a PostgreSQL feature that lets the INSERT return column values
// generated by the database (e.g. the auto-generated UUID primary key
// session_id and the default timestamp columns). This avoids a second query
// just to read back the values the database assigned.
func (r *SessionRepo) Create(ctx context.Context, s *model.Session) error {
	// Query: insert a new session and get back the server-generated fields.
	const q = `
		INSERT INTO sessions (session_token, agent_id, status, project_dir, git_branch)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING session_id, started_at, last_event_at`

	row := r.db.QueryRow(ctx, q,
		s.SessionToken,
		s.AgentID,
		s.Status,
		s.ProjectDir,
		s.GitBranch,
	)
	if err := row.Scan(&s.SessionID, &s.StartedAt, &s.LastEventAt); err != nil {
		return fmt.Errorf("SessionRepo.Create: %w", err)
	}
	return nil
}

// Close marks a session as closed and records the ended_at timestamp.
func (r *SessionRepo) Close(ctx context.Context, sessionID uuid.UUID) error {
	const q = `
		UPDATE sessions
		SET status   = 'closed',
		    ended_at = NOW()
		WHERE session_id = $1`

	_, err := r.db.Exec(ctx, q, sessionID)
	if err != nil {
		return fmt.Errorf("SessionRepo.Close: %w", err)
	}
	return nil
}

// UpdateLastEvent sets last_event_at to NOW() and increments event_count by one.
func (r *SessionRepo) UpdateLastEvent(ctx context.Context, sessionID uuid.UUID) error {
	const q = `
		UPDATE sessions
		SET last_event_at = NOW(),
		    event_count   = event_count + 1
		WHERE session_id = $1`

	_, err := r.db.Exec(ctx, q, sessionID)
	if err != nil {
		return fmt.Errorf("SessionRepo.UpdateLastEvent: %w", err)
	}
	return nil
}

// FindTimedOut returns active sessions whose last_event_at is older than the
// given timeout duration. These are sessions that have gone silent for too long
// and should be automatically closed by the timeout worker.
//
// The SQL expression "NOW() - last_event_at > $1::interval" computes the
// elapsed time since the last event and compares it to the Go duration (cast
// to a PostgreSQL interval). Only sessions still marked 'active' are returned.
func (r *SessionRepo) FindTimedOut(ctx context.Context, timeout time.Duration) ([]*model.Session, error) {
	// Query: find all active sessions that have been idle longer than the timeout.
	const q = `
		SELECT session_id, session_token, agent_id, status,
		       project_dir, git_branch,
		       started_at, ended_at, last_event_at,
		       event_count, pinned
		FROM sessions
		WHERE status = 'active'
		  AND NOW() - last_event_at > $1::interval`

	rows, err := r.db.Query(ctx, q, timeout.String())
	if err != nil {
		return nil, fmt.Errorf("SessionRepo.FindTimedOut: %w", err)
	}
	defer rows.Close()

	var sessions []*model.Session
	for rows.Next() {
		s, err := scanSession(rows)
		if err != nil {
			return nil, fmt.Errorf("SessionRepo.FindTimedOut scan: %w", err)
		}
		sessions = append(sessions, s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("SessionRepo.FindTimedOut rows: %w", err)
	}
	return sessions, nil
}

// GetByID retrieves a session by its UUID. Returns nil, nil when not found.
func (r *SessionRepo) GetByID(ctx context.Context, sessionID uuid.UUID) (*model.Session, error) {
	const q = `
		SELECT session_id, session_token, agent_id, status,
		       project_dir, git_branch,
		       started_at, ended_at, last_event_at,
		       event_count, pinned
		FROM sessions
		WHERE session_id = $1`

	row := r.db.QueryRow(ctx, q, sessionID)
	s, err := scanSession(row)
	if err != nil {
		if isNoRows(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("SessionRepo.GetByID: %w", err)
	}
	return s, nil
}

// SessionListResult holds a page of sessions together with the total
// un-paginated count.
type SessionListResult struct {
	Sessions []*model.Session
	Total    int
}

// List returns a paginated slice of sessions matching the given filters, along
// with the total count of matching rows (ignoring limit/offset).
//
// This method uses a "composable WHERE builder" pattern: instead of writing
// many different SQL queries for every filter combination, it dynamically
// assembles the WHERE clause at runtime. For each non-nil/non-empty filter
// field, a condition string like "agent_id = $1" is appended to a slice, and
// the corresponding value is appended to the args slice. Finally all conditions
// are joined with " AND ". This keeps the code DRY and makes it trivial to add
// new filters in the future.
//
// The argN helper produces the next "$N" placeholder and appends the value,
// ensuring that placeholder numbering always stays in sync with the args slice.
func (r *SessionRepo) List(ctx context.Context, filters SessionFilters, limit, offset int) (*SessionListResult, error) {
	// Build the WHERE clause dynamically from the provided filters.
	var (
		conds []string // individual SQL conditions, e.g. "agent_id = $1"
		args  []any    // corresponding parameter values, matched by position
	)
	// argN appends a value to args and returns the next "$N" placeholder string.
	argN := func(v any) string {
		args = append(args, v)
		return fmt.Sprintf("$%d", len(args))
	}

	if filters.AgentID != "" {
		conds = append(conds, "agent_id = "+argN(filters.AgentID))
	}
	if filters.Status != "" {
		conds = append(conds, "status = "+argN(filters.Status))
	}
	if filters.ProjectDir != nil {
		conds = append(conds, "project_dir = "+argN(*filters.ProjectDir))
	}
	if filters.Pinned != nil {
		conds = append(conds, "pinned = "+argN(*filters.Pinned))
	}

	where := ""
	if len(conds) > 0 {
		where = "WHERE " + strings.Join(conds, " AND ")
	}

	countQ := "SELECT COUNT(*) FROM sessions " + where

	var total int
	if err := r.db.QueryRow(ctx, countQ, args...).Scan(&total); err != nil {
		return nil, fmt.Errorf("SessionRepo.List count: %w", err)
	}

	listQ := fmt.Sprintf(`
		SELECT session_id, session_token, agent_id, status,
		       project_dir, git_branch,
		       started_at, ended_at, last_event_at,
		       event_count, pinned
		FROM sessions
		%s
		ORDER BY started_at DESC
		LIMIT %s OFFSET %s`,
		where,
		argN(limit),
		argN(offset),
	)

	rows, err := r.db.Query(ctx, listQ, args...)
	if err != nil {
		return nil, fmt.Errorf("SessionRepo.List query: %w", err)
	}
	defer rows.Close()

	var sessions []*model.Session
	for rows.Next() {
		s, err := scanSession(rows)
		if err != nil {
			return nil, fmt.Errorf("SessionRepo.List scan: %w", err)
		}
		sessions = append(sessions, s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("SessionRepo.List rows: %w", err)
	}

	return &SessionListResult{Sessions: sessions, Total: total}, nil
}

// scanner is the common interface shared by pgx.Row (single row from QueryRow)
// and pgx.Rows (iterator from Query). By abstracting over this interface,
// scanSession can be reused for both single-row and multi-row result sets
// without code duplication.
type scanner interface {
	Scan(dest ...any) error
}

// scanSession scans one session row into a model.Session. It reads columns in
// the exact order they appear in every SELECT statement in this file.
func scanSession(row scanner) (*model.Session, error) {
	s := &model.Session{}
	err := row.Scan(
		&s.SessionID, &s.SessionToken, &s.AgentID, &s.Status,
		&s.ProjectDir, &s.GitBranch,
		&s.StartedAt, &s.EndedAt, &s.LastEventAt,
		&s.EventCount, &s.Pinned,
	)
	if err != nil {
		return nil, err
	}
	return s, nil
}

// isNoRows reports whether err is the pgx "no rows" sentinel.
// pgx returns a specific error when QueryRow().Scan() finds zero rows.
// We check the error message string to avoid importing the pgx package directly
// in files that otherwise only need pgxpool.
func isNoRows(err error) bool {
	return err != nil && err.Error() == "no rows in result set"
}
